import { Dimensions, Platform, StyleSheet } from 'react-native';
import { colors } from '../Constants/colors';

const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    position: 'relative',
  },
  screen_bg: {
    position: 'absolute',
    width: screenWidth,
    height: screenHeight,
    top: 0,
    left: 0,
  },
  container: {
    // width: '80%',
    padding: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.card_bg,
  },
  btn_greater: {
    width: 90,
    backgroundColor: 'rgba(187,247,77,.1)',
    borderColor: 'rgba(182,252,53,.5)',
    borderTopColor: 'rgba(89,139,247,0)',
    borderBottomColor: 'rgba(89,139,247,0)',
    borderRadius: 5,
    borderWidth: 1,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    elevation: 20,
  },
  btn_lower: {
    width: 90,
    marginTop: 10,
    borderColor: 'rgba(247,230,64,.5)',

    borderTopColor: 'rgba(89,139,247,0)',
    borderBottomColor: 'rgba(89,139,247,0)',
    borderRadius: 5,
    backgroundColor: 'rgba(247,84,52,.1)',
    borderWidth: 1,
    borderLeftWidth: 1,
    elevation: 20,
  },
  card_body: {
    backgroundColor: 'rgba(247,188,52,0)',
    borderColor: 'rgba(235,9,50,0)',
    borderTopColor: 'rgba(235,9,50,0)',
    borderBottomColor: 'rgba(235,9,50,0)',
    borderRadius: 5,
    maxWidth: '80%',
  },

  exitButton: {
    // marginTop: -30,
    marginBottom: 50,
    paddingHorizontal: 10,
    // backgroundColor: 'black',
    borderColor: 'rgba(127,97,236,0)',
    borderRightWidth: 0,
    borderBottomWidth: 0,
    // borderLeftWidth: 0,
    // borderTopColor: 'rgba(126,240,28,.2)',
    // borderBottomColor: 'rgba(126,240,28,.2)',
    borderWidth: 1,
    borderRadius: 3,
  },
  exitTitle: {
    padding: 3,
    paddingVertical: 7,
    paddingTop: 12,
    fontSize: 8,
    color: 'rgba(247,230,64,.9)',
    // opacity: 0,
    fontFamily: 'press-start',
  },
  guess_title: {
    color: 'rgba(247,230,64,.5)',
    fontFamily: 'press-start',
    fontSize: 10,
    marginTop: 20,
  },
  guess_count: {
    color: 'rgba(247,230,64,.5)',
  },
  number: {
    position: 'relative',
    marginTop: 20,
    maxHeight: '100%',
    width: 180,
    height: 100,
    borderColor: 'rgba(45,79,235,0)',
    // borderBottomColor: 'rgba(45,79,235,1)',
    borderWidth: 1,
    borderRadius: 3,
    padding: 20,
    // overflow: 'hidden',
  },
  number_value_container: {
    position: 'relative',
    minWidth: '100%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    // minHeight: '100%',
  },
  numberValue: {
    fontSize: 50,
    // color: 'rgba(21,41,83,1)',
    color: 'rgba(120,111,31,.9)',
    width: '100%',
    textAlign: 'center',
    paddingTop: 30,
    fontFamily: 'press-start',
  },
  number_value_shadow: {
    position: 'absolute',
    top: -12,
    left: 0,
    fontSize: 51,
    width: '100%',
    textAlign: 'center',
    paddingTop: 30,
    fontFamily: 'press-start',
    color: 'rgba(187,247,77,.8)',
  },

  number_dash_left: {
    position: 'absolute',
    width: 10,
    height: 2,
    left: -15,
    top: 40,
    borderRadius: 3,
    // backgroundColor: 'rgba(56,56,56,.3)',
  },
  number_dash_right: {
    position: 'absolute',
    width: 10,
    height: 2,
    left: 170,
    top: 40,
    borderRadius: 3,
    // backgroundColor: 'rgba(56,56,56,.3)',
  },
  top_line: {
    position: 'absolute',
    top: 0,
    left: '50%',
    width: 50,
    height: 5,
    backgroundColor: 'rgba(56,56,56,.8)',
  },
  bottom_line: {
    position: 'absolute',
    top: 95,
    left: 50,
    width: 50,
    height: 5,
    backgroundColor: 'rgba(56,56,56,.8)',
  },

  gameOverNumber: {
    fontSize: 15,
    fontFamily: 'press-start',
    color: 'white',
  },
  card: {
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    backgroundColor: 'rgba(40,70,240,0)',
    borderColor: 'rgba(37,65,225,0)',
  },

  guessList: {
    // flexDirection: 'column',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    // borderTopColor: 'rgba(125,95,233,0.2)',
    borderWidth: 0,
    height: '20%',
    width: '50%',
    marginTop: 10,
    paddingTop: 5,
    paddingHorizontal: 5,
    borderRadius: 5,
    // borderTopLeftRadius: 10,
    // borderTopRightRadius: 10,
    overflow: 'hidden',
  },

  list_lamp: {
    position: 'absolute',
    width: '10%',
    height: '10%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 2,
    borderWidth: 1,
  },

  list_bg: {
    position: 'absolute',
    minWidth: '100%',
    minHeight: '100%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    margin: 0,
  },

  listItem: {
    marginVertical: 8,
    padding: 5,
    borderColor: 'rgba(247,230,64,.2)',
    borderTopColor: 'rgba(247,230,64,.8)',
    borderWidth: 1,
    backgroundColor: 'rgba(247,230,64,.1)',
    margin: 5,
    borderRadius: 5,
    // opacity: 1,
  },
  animation: {
    backgroundColor: 'black',
  },
  text: {
    fontFamily: 'press-start',
    paddingTop: 5,
    fontSize: 14,
    color: 'white',
  },
});
